# Config file for automatic testing at travis-ci.org
language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r ./g/requirements.txt

# command to run tests
script: python ./g/setup.py test
